channels:
  - conda-forge
  - defaults

# Compatibility chart: https://stackoverflow.com/questions/62690377/tensorflow-compatibility-with-keras
dependencies:
  - python=3.7
  - ipykernel=6.*
  - tensorflow-gpu=1.15.*
  - pip=23.*
  - pip:
    - keras==2.3.1
    - h5py==2.10.0
    - protobuf==3.20.3
    - matplotlib==3.1.3
    - scikit-image==0.16.2
    - opencv-python==3.4.8.29
    - nbconvert==7.6.0
